version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///database.db
      - JWT_SECRET_KEY=super-secret-key-that-is-very-long-and-secure-12345
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - DOCKER_BUILD=true
    volumes: # <-- ДОБАВЬТЕ ЭТИ СТРОКИ
      - ./frontend:/app
      - /app/node_modules # Чтобы локальная папка node_modules не затерла контейнерную
    depends_on:
      - backend
